#!/bin/bash
# Script to manually create Homebrew formula after a release

set -e

VERSION=${1:-"1.0.0"}
REPO="vib795/convert-video-formats"
PROJECT_NAME="convert-video-formats"
TAP_REPO="vib795/homebrew-tap"

echo "Creating Homebrew formula for version $VERSION"
echo ""

# Function to download and calculate SHA256
get_sha256() {
    local url=$1
    local filename=$(basename "$url")
    echo "Downloading $filename to calculate SHA256..." >&2

    if curl -sL "$url" -o "/tmp/$filename"; then
        shasum -a 256 "/tmp/$filename" | awk '{print $1}'
    else
        echo "ERROR: Failed to download $url" >&2
        return 1
    fi
}

# Calculate SHA256 for each platform
echo "Calculating SHA256 checksums..."
SHA_DARWIN_ARM64=$(get_sha256 "https://github.com/$REPO/releases/download/v$VERSION/${PROJECT_NAME}_${VERSION}_darwin_arm64.tar.gz")
SHA_DARWIN_AMD64=$(get_sha256 "https://github.com/$REPO/releases/download/v$VERSION/${PROJECT_NAME}_${VERSION}_darwin_amd64.tar.gz")
SHA_LINUX_ARM64=$(get_sha256 "https://github.com/$REPO/releases/download/v$VERSION/${PROJECT_NAME}_${VERSION}_linux_arm64.tar.gz")
SHA_LINUX_AMD64=$(get_sha256 "https://github.com/$REPO/releases/download/v$VERSION/${PROJECT_NAME}_${VERSION}_linux_amd64.tar.gz")

echo ""
echo "SHA256 checksums calculated:"
echo "  Darwin ARM64:  $SHA_DARWIN_ARM64"
echo "  Darwin AMD64:  $SHA_DARWIN_AMD64"
echo "  Linux ARM64:   $SHA_LINUX_ARM64"
echo "  Linux AMD64:   $SHA_LINUX_AMD64"
echo ""

if [ -z "$SHA_DARWIN_ARM64" ] || [ -z "$SHA_DARWIN_AMD64" ]; then
    echo "Error: Failed to calculate SHA256 checksums"
    exit 1
fi

# Create formula
cat > /tmp/convert-vid.rb << EOF
# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ConvertVid < Formula
  desc "A fast CLI tool for converting video files between different formats"
  homepage "https://github.com/$REPO"
  version "$VERSION"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/$REPO/releases/download/v$VERSION/${PROJECT_NAME}_${VERSION}_darwin_arm64.tar.gz"
      sha256 "$SHA_DARWIN_ARM64"

      def install
        bin.install "convert-vid"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/$REPO/releases/download/v$VERSION/${PROJECT_NAME}_${VERSION}_darwin_amd64.tar.gz"
      sha256 "$SHA_DARWIN_AMD64"

      def install
        bin.install "convert-vid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/$REPO/releases/download/v$VERSION/${PROJECT_NAME}_${VERSION}_linux_arm64.tar.gz"
      sha256 "$SHA_LINUX_ARM64"

      def install
        bin.install "convert-vid"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/$REPO/releases/download/v$VERSION/${PROJECT_NAME}_${VERSION}_linux_amd64.tar.gz"
      sha256 "$SHA_LINUX_AMD64"

      def install
        bin.install "convert-vid"
      end
    end
  end

  depends_on "ffmpeg"

  test do
    system "#{bin}/convert-vid", "version"
  end
end
EOF

echo "Formula created at /tmp/convert-vid.rb"
echo ""
echo "========================================="
cat /tmp/convert-vid.rb
echo "========================================="
echo ""
echo "Next steps:"
echo "1. Copy the formula to your tap:"
echo "   cp /tmp/convert-vid.rb ~/path/to/homebrew-tap/Formula/"
echo ""
echo "2. Commit and push:"
echo "   cd ~/path/to/homebrew-tap"
echo "   git add Formula/convert-vid.rb"
echo "   git commit -m \"Update convert-vid formula v$VERSION\""
echo "   git push origin main"
echo ""
echo "3. Update tap and reinstall:"
echo "   brew uninstall convert-vid 2>/dev/null || true"
echo "   brew untap $TAP_REPO 2>/dev/null || true"
echo "   brew tap $TAP_REPO"
echo "   brew install convert-vid"
echo ""
echo "4. Test:"
echo "   convert-vid version"